#!/usr/bin/env bash
# =============================================================================
# configure.sh — Interactive environment setup for the watsonx.data SIEM demo
# =============================================================================
# Asks every question needed to build a working .env, installs Python + Node
# dependencies, tests the Presto connection, and writes the file for you.
#
# Usage:
#   chmod +x scripts/configure.sh
#   ./scripts/configure.sh
#
# Re-run at any time to update your configuration.
# =============================================================================
set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RESET='\033[0m'; BOLD='\033[1m'
GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BLUE='\033[0;34m'; DIM='\033[2m'

banner()  { echo -e "\n${BOLD}${BLUE}── $* ${RESET}"; }
info()    { echo -e "  ${CYAN}·${RESET} $*"; }
ok()      { echo -e "  ${GREEN}✔${RESET}  $*"; }
warn()    { echo -e "  ${YELLOW}⚠${RESET}  $*"; }
err()     { echo -e "  ${RED}✘${RESET}  $*"; }
ask()     { echo -e "  ${BOLD}$*${RESET}"; }          # question label
hint()    { echo -e "  ${DIM}$*${RESET}"; }           # grey hint text

# ── Working directory: always repo root ──────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="$ROOT_DIR/.env"

# ── Read a line with a default value ─────────────────────────────────────────
# Usage: prompt_default VAR "Question" "default"
prompt_default() {
    local varname="$1" question="$2" default="$3"
    ask "$question"
    [ -n "$default" ] && hint "  (press Enter to accept: $default)"
    read -r -p "  → " input
    input="${input:-$default}"
    printf -v "$varname" '%s' "$input"
}

# ── Read a line — blank is allowed (no default hint shown) ───────────────────
prompt_optional() {
    local varname="$1" question="$2"
    ask "$question"
    hint "  (press Enter to leave blank)"
    read -r -p "  → " input
    printf -v "$varname" '%s' "$input"
}

# ── Read a masked password (no echo) ─────────────────────────────────────────
prompt_secret() {
    local varname="$1" question="$2"
    ask "$question"
    hint "  (input hidden)"
    read -r -s -p "  → " input
    echo ""   # newline after hidden input
    printf -v "$varname" '%s' "$input"
}

# ── Yes/No prompt, returns 0 for yes, 1 for no ───────────────────────────────
confirm() {
    local question="$1" default="${2:-y}"
    local prompt_str
    [ "$default" = "y" ] && prompt_str="[Y/n]" || prompt_str="[y/N]"
    ask "$question $prompt_str"
    read -r -p "  → " yn
    yn="${yn:-$default}"
    [[ "$yn" =~ ^[Yy] ]]
}

# ── Read current value of a key from .env (empty string if absent) ────────────
current_env() {
    local key="$1"
    if [ -f "$ENV_FILE" ]; then
        grep -E "^${key}=" "$ENV_FILE" | head -1 | cut -d= -f2- | sed "s/^['\"]//;s/['\"]$//"
    fi
}

# ── Write the final .env file ─────────────────────────────────────────────────
write_env() {
    cat > "$ENV_FILE" << EOF
# =============================================================================
# watsonx.data Presto ↔ SIEM Integration Demo — Environment
# Generated by scripts/configure.sh on $(date)
# NEVER commit this file to source control.
# =============================================================================

# ── Demo mode ─────────────────────────────────────────────────────────────────
# "live"  → queries run against your real Presto endpoint
# "mock"  → 100% synthetic data; Presto connection is ignored
DEMO_MODE=${DEMO_MODE}

PORT=${PORT}
HOST=0.0.0.0

# ── watsonx.data Presto connection ────────────────────────────────────────────
PRESTO_HOST=${PRESTO_HOST}
PRESTO_PORT=${PRESTO_PORT}
PRESTO_USE_SSL=${PRESTO_USE_SSL}
PRESTO_SSL_VERIFY=${PRESTO_SSL_VERIFY}

# ── Authentication ────────────────────────────────────────────────────────────
# CP4D/watsonx.data Presto requires a bearer token, not HTTP Basic Auth.
# Option A: supply PRESTO_BEARER_TOKEN directly (paste a CP4D access token).
# Option B: supply PRESTO_USER + PRESTO_PASSWORD — the backend will call
#           https://<PRESTO_CPD_HOST>/icp4d-api/v1/authorize to exchange them
#           for a token automatically on startup.
# PRESTO_CPD_HOST is the CP4D console hostname (often the same as PRESTO_HOST).
PRESTO_USER=${PRESTO_USER}
PRESTO_PASSWORD=${PRESTO_PASSWORD}
PRESTO_BEARER_TOKEN=${PRESTO_BEARER_TOKEN}
PRESTO_CPD_HOST=${PRESTO_CPD_HOST}

# ── Session defaults (catalog/schema used when SQL cannot be parsed) ──────────
PRESTO_CATALOG=${PRESTO_CATALOG}
PRESTO_SCHEMA=${PRESTO_SCHEMA}

# ── SIEM event forwarding (leave blank for local-only) ───────────────────────
SIEM_FORWARD_HOST=${SIEM_FORWARD_HOST}
SIEM_FORWARD_PORT=${SIEM_FORWARD_PORT}
SIEM_FORWARD_PROTOCOL=${SIEM_FORWARD_PROTOCOL}
SIEM_FORMAT=${SIEM_FORMAT}

# ── Frontend ──────────────────────────────────────────────────────────────────
VITE_API_BASE_URL=http://localhost:${PORT}/api
VITE_DEMO_TITLE="${VITE_DEMO_TITLE}"
VITE_DEMO_CLIENT_CODE=${VITE_DEMO_CLIENT_CODE}
EOF
}

# ── Test Presto reachability using Python + trino ─────────────────────────────
test_presto_connection() {
    info "Testing Presto connection…"
    local py_script
    py_script=$(cat << 'PYEOF'
import sys, os

host   = os.environ.get("T_HOST", "")
port   = int(os.environ.get("T_PORT", "8443"))
user   = os.environ.get("T_USER", "ibmacp")
passwd = os.environ.get("T_PASS", "")
token  = os.environ.get("T_TOKEN", "")
use_ssl = os.environ.get("T_SSL", "false").lower() == "true"
verify  = os.environ.get("T_VERIFY", "true").lower() == "true"

def full_message(exc):
    """
    Walk the exception chain, deduplicating messages that repeat verbatim
    (common in urllib3/requests/trino chains) and returning only distinct lines.
    """
    parts = []
    seen_msgs = set()
    seen_ids  = set()
    e = exc
    while e is not None and id(e) not in seen_ids:
        seen_ids.add(id(e))
        msg = type(e).__name__ + ": " + str(e)
        # Use the str(e) part as the dedup key so repeated wrappers are collapsed
        key = str(e).strip()
        if key not in seen_msgs:
            seen_msgs.add(key)
            parts.append(msg)
        e = e.__cause__ or e.__context__
    return "\n".join(parts)

def get_cpd_token(cpd_host, user, passwd, verify):
    """
    Exchange CP4D username + password for a bearer token via
    POST /icp4d-api/v1/authorize.  Returns the token string.
    CP4D/watsonx.data Presto does NOT accept HTTP Basic Auth —
    it only accepts Authorization: Bearer <cpd-token>.
    """
    import urllib.request, urllib.error, json, ssl
    url = f"https://{cpd_host}/icp4d-api/v1/authorize"
    payload = json.dumps({"username": user, "password": passwd}).encode()
    req = urllib.request.Request(url, data=payload,
                                 headers={"Content-Type": "application/json"})
    ctx = ssl.create_default_context()
    if not verify:
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
    with urllib.request.urlopen(req, context=ctx, timeout=10) as resp:
        body = json.loads(resp.read())
    t = body.get("token") or body.get("access_token")
    if not t:
        raise ValueError(f"No token in CP4D response: {list(body.keys())}")
    return t

try:
    import urllib.request, json, ssl, time

    # CP4D/watsonx.data Presto requires a bearer token, not HTTP Basic Auth.
    # If only a password was supplied, exchange it for a CP4D token first.
    if not token and passwd:
        cpd_host = os.environ.get("T_CPD_HOST", host)
        print(f"INFO:Fetching CP4D token from https://{cpd_host}/icp4d-api/v1/authorize …",
              file=sys.stderr)
        token = get_cpd_token(cpd_host, user, passwd, verify)
        print(f"INFO:Token obtained (first 12 chars): {token[:12]}…", file=sys.stderr)

    # Use the Presto HTTP REST protocol directly with X-Presto-User.
    # The trino Python client sends X-Trino-User which CP4D Presto (Java)
    # does not recognise, causing "400: User must be set".
    protocol = "https" if use_ssl else "http"
    url = f"{protocol}://{host}:{port}/v1/statement"
    headers = {
        "X-Presto-User": user,
        "X-Presto-Source": "watsonx-data-siem-demo",
        "Content-Type": "text/plain",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    ctx = ssl.create_default_context()
    if not verify:
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

    def presto_post(u, body=None, hdrs=None):
        req = urllib.request.Request(u, data=body, headers=hdrs or {})
        return urllib.request.urlopen(req, context=ctx, timeout=15)

    req_body = b"SHOW CATALOGS"
    with presto_post(url, req_body, headers) as r:
        data = json.loads(r.read())

    # Poll nextUri until terminal state
    all_rows = []
    columns = []
    while True:
        if data.get("columns") and not columns:
            columns = [c["name"] for c in data["columns"]]
        if data.get("data"):
            all_rows.extend(data["data"])
        state = data.get("stats", {}).get("state", "")
        next_uri = data.get("nextUri")
        if state in ("FINISHED", "FAILED", "CANCELED") or not next_uri:
            break
        time.sleep(0.2)
        with urllib.request.urlopen(
            urllib.request.Request(next_uri, headers={"Authorization": headers.get("Authorization", "")}),
            context=ctx, timeout=15
        ) as r:
            data = json.loads(r.read())

    catalogs = [row[0] for row in all_rows if row]
    print("OK:" + ",".join(catalogs))
except Exception as e:
    print("ERR:" + full_message(e))
PYEOF
)
    local result ok_line err_line

    # stderr (INFO progress lines, urllib3 warnings) goes to fd 3 → terminal.
    # stdout (the single OK:… or ERR:… line) is captured in $result.
    result=$(T_HOST="$PRESTO_HOST" T_PORT="$PRESTO_PORT" T_USER="$PRESTO_USER" \
             T_PASS="$PRESTO_PASSWORD" T_TOKEN="$PRESTO_BEARER_TOKEN" \
             T_CPD_HOST="${PRESTO_CPD_HOST:-$PRESTO_HOST}" \
             T_SSL="$PRESTO_USE_SSL" T_VERIFY="$PRESTO_SSL_VERIFY" \
             python3 -c "$py_script" 2>&3)

    # Extract the sentinel lines regardless of any extra output mixed in
    ok_line=$(echo "$result"  | grep '^OK:'  | tail -1)
    err_line=$(echo "$result" | grep '^ERR:' | tail -1)

    if [ -n "$ok_line" ]; then
        local catalogs="${ok_line#OK:}"
        ok "Connection successful!"
        info "Catalogs visible to user '${PRESTO_USER}': ${catalogs}"
        DETECTED_CATALOGS="$catalogs"
        return 0
    else
        err "Connection failed:"
        local errmsg="${err_line#ERR:}"
        # Fall back to full output when there is no ERR: line (e.g. Python crash)
        [ -z "$errmsg" ] && errmsg="$result"
        while IFS= read -r line; do
            echo -e "    ${RED}${line}${RESET}"
        done <<< "$errmsg"
        DETECTED_CATALOGS=""
        return 1
    fi
}

# =============================================================================
#  MAIN
# =============================================================================

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║   watsonx.data Presto ↔ SIEM Demo  ·  Interactive Setup     ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${RESET}"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — Prerequisites
# ─────────────────────────────────────────────────────────────────────────────
banner "Step 1 of 5 — Checking prerequisites"

command -v python3 >/dev/null 2>&1 || { err "python3 not found — install Python 3.9+ from https://python.org"; exit 1; }
ok "Python $(python3 --version 2>&1 | awk '{print $2}')"

command -v node >/dev/null 2>&1 || { err "node not found — install Node.js 18+ from https://nodejs.org"; exit 1; }
ok "Node.js $(node --version)"

command -v npm >/dev/null 2>&1 || { err "npm not found"; exit 1; }
ok "npm $(npm --version)"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — Install dependencies
# ─────────────────────────────────────────────────────────────────────────────
banner "Step 2 of 5 — Installing dependencies"

if [ ! -d "backend/.venv" ]; then
    info "Creating Python virtual environment…"
    python3 -m venv backend/.venv
    ok "Created backend/.venv"
else
    ok "Reusing existing backend/.venv"
fi

info "Installing backend packages (fastapi, uvicorn, trino, …)"
source backend/.venv/bin/activate
pip install --quiet --upgrade pip
pip install --quiet -r backend/requirements.txt
ok "Backend packages installed  (trino $(python3 -c 'import trino; print(trino.__version__)'))"

info "Installing frontend packages (React, Carbon, …)"
cd frontend && npm install --silent && cd ..
ok "Frontend packages installed"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — Demo mode
# ─────────────────────────────────────────────────────────────────────────────
banner "Step 3 of 5 — Demo mode"

hint "  'live'  → queries run against real watsonx.data Presto"
hint "  'mock'  → 100% synthetic data, no Presto connection needed"
echo ""
prompt_default DEMO_MODE "Demo mode?" "$(current_env DEMO_MODE || echo live)"

# Ports
prompt_default PORT "Backend port?" "$(current_env PORT || echo 8000)"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 — Presto connection (only if live mode)
# ─────────────────────────────────────────────────────────────────────────────
PRESTO_HOST=""
PRESTO_PORT="8443"
PRESTO_USE_SSL="true"
PRESTO_SSL_VERIFY="false"
PRESTO_USER="ibmacp"
PRESTO_PASSWORD=""
PRESTO_BEARER_TOKEN=""
PRESTO_CPD_HOST=""
PRESTO_CATALOG="iceberg_data"
PRESTO_SCHEMA="finance"
DETECTED_CATALOGS=""

if [ "$DEMO_MODE" = "live" ]; then
    banner "Step 4 of 5 — Presto connection"

    # ── Host ──
    hint "  Find it in the watsonx.data console under Infrastructure → Connection details."
    hint "  Example:       ibm-lh-presto-svc-cpd-watsonx-data.apps.my-cluster.com"
    prompt_default PRESTO_HOST "Presto hostname (no protocol, no port):" \
        "$(current_env PRESTO_HOST)"

    # ── Port ──
    echo ""
    hint "  External route → 443   |   Internal service → 8443"
    prompt_default PRESTO_PORT "Presto port:" \
        "$(current_env PRESTO_PORT || echo 443)"

    # ── SSL ──
    echo ""
    if confirm "Use TLS/HTTPS?" "y"; then
        PRESTO_USE_SSL="true"
        if confirm "Verify TLS certificate? (say No for self-signed certs)" "n"; then
            PRESTO_SSL_VERIFY="true"
        else
            PRESTO_SSL_VERIFY="false"
        fi
    else
        PRESTO_USE_SSL="false"
        PRESTO_SSL_VERIFY="false"
    fi

    # ── Authentication ──
    echo ""
    banner "  Authentication method"
    hint "  NOTE: CP4D/watsonx.data Presto does NOT accept HTTP Basic Auth."
    hint "  It authenticates via a CP4D bearer token obtained from /icp4d-api/v1/authorize."
    echo ""
    hint "  1) Username + password  — the script fetches the CP4D token automatically"
    hint "  2) Bearer token         — paste a token you already have (preferred)"
    echo ""
    prompt_default AUTH_METHOD "Choose [1/2]:" "1"

    prompt_default PRESTO_USER "Presto / CP4D username:" \
        "$(current_env PRESTO_USER || echo ibmacp)"

    if [ "$AUTH_METHOD" = "2" ]; then
        hint "  Obtain a token with:"
        hint "    curl -k -X POST https://<cpd-host>/icp4d-api/v1/authorize \\"
        hint "         -H 'Content-Type: application/json' \\"
        hint "         -d '{\"username\":\"ibmacp\",\"password\":\"...\"}' \\"
        hint "    | python3 -c \"import sys,json; print(json.load(sys.stdin)['token'])\""
        echo ""
        prompt_secret PRESTO_BEARER_TOKEN "Bearer token:"
        PRESTO_PASSWORD=""
        PRESTO_CPD_HOST=""
    else
        hint "  The CP4D console hostname is used to fetch the token."
        hint "  It is often the same as the Presto hostname, but may differ."
        hint "  Example: cpd-watsonx-data.apps.my-cluster.com"
        echo ""
        prompt_default PRESTO_CPD_HOST "CP4D console hostname (for token exchange):" \
            "$(current_env PRESTO_CPD_HOST || echo "$PRESTO_HOST")"
        prompt_secret PRESTO_PASSWORD "CP4D password:"
        PRESTO_BEARER_TOKEN=""
    fi

    # ── Test connection ──
    # fd 3 → terminal: Python can write progress/INFO lines to stderr (2>&3)
    # without them mixing into $result (which only captures stdout).
    exec 3>&1
    echo ""
    banner "  Testing Presto connection"
    if test_presto_connection; then
        # ── Default catalog / schema from live discovery ──
        echo ""
        banner "  Default catalog & schema"
        hint "  These are used as the Presto session default and SQL-parsing fallback."
        hint "  All catalogs are always discovered — this is just the starting point."
        if [ -n "$DETECTED_CATALOGS" ]; then
            info "Available catalogs: $DETECTED_CATALOGS"
        fi
        prompt_default PRESTO_CATALOG "Default catalog:" \
            "$(current_env PRESTO_CATALOG || echo iceberg_data)"
        prompt_default PRESTO_SCHEMA  "Default schema in that catalog:" \
            "$(current_env PRESTO_SCHEMA || echo finance)"
    else
        echo ""
        warn "Could not reach Presto. You can still continue — the demo will"
        warn "run in simulation fallback until the connection is fixed."
        echo ""
        if confirm "Continue and save the connection details anyway?" "y"; then
            prompt_default PRESTO_CATALOG "Default catalog (session fallback):" \
                "$(current_env PRESTO_CATALOG || echo iceberg_data)"
            prompt_default PRESTO_SCHEMA  "Default schema (session fallback):" \
                "$(current_env PRESTO_SCHEMA || echo finance)"
        else
            err "Aborting. Fix the hostname/credentials and re-run."
            exit 1
        fi
    fi

else
    banner "Step 4 of 5 — Presto connection (skipped — mock mode)"
    ok "No connection details needed for mock mode."
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 5 — SIEM forwarding (optional)
# ─────────────────────────────────────────────────────────────────────────────
banner "Step 5 of 5 — SIEM event forwarding (optional)"
hint "  Forward LEEF/CEF audit events to an external SIEM (QRadar, Splunk, Sentinel)."
hint "  Leave blank to keep events local — this is the default for demos."
echo ""

if confirm "Forward events to an external SIEM?" "n"; then
    prompt_default SIEM_FORWARD_HOST "SIEM host (IP or hostname):" \
        "$(current_env SIEM_FORWARD_HOST)"
    prompt_default SIEM_FORWARD_PORT "SIEM syslog port:" \
        "$(current_env SIEM_FORWARD_PORT || echo 514)"
    hint "  Protocol options: UDP  TCP  TLS"
    prompt_default SIEM_FORWARD_PROTOCOL "Protocol:" \
        "$(current_env SIEM_FORWARD_PROTOCOL || echo UDP)"
    hint "  Format options: LEEF_2_0  CEF"
    prompt_default SIEM_FORMAT "Event format:" \
        "$(current_env SIEM_FORMAT || echo LEEF_2_0)"
else
    ok "Skipping SIEM forwarding."
    SIEM_FORWARD_HOST=""
    SIEM_FORWARD_PORT="514"
    SIEM_FORWARD_PROTOCOL="UDP"
    SIEM_FORMAT="LEEF_2_0"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Frontend labels (no need to ask — keep sensible defaults)
# ─────────────────────────────────────────────────────────────────────────────
VITE_DEMO_TITLE="watsonx.data Presto & SIEM Integration Console"
VITE_DEMO_CLIENT_CODE="DEMO-WXD-SIEM"

# ─────────────────────────────────────────────────────────────────────────────
# Write .env
# ─────────────────────────────────────────────────────────────────────────────
echo ""
banner "Writing .env"

# Backup existing .env
if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "${ENV_FILE}.bak"
    info "Backed up existing .env → .env.bak"
fi

write_env
ok "Written to $ENV_FILE"

# ─────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║   Configuration complete — how to start the demo            ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "${CYAN}  Terminal 1 — backend:${RESET}"
echo "    source backend/.venv/bin/activate"
echo "    uvicorn backend.main:app --port ${PORT} --reload"
echo ""
echo -e "${CYAN}  Terminal 2 — frontend:${RESET}"
echo "    cd frontend && npm run dev"
echo ""
echo -e "${CYAN}  Open the demo:${RESET}"
echo "    http://localhost:3000"
echo ""
if [ "$DEMO_MODE" = "live" ]; then
    echo -e "${CYAN}  Verify Presto connectivity (once the backend is running):${RESET}"
    echo "    curl http://localhost:${PORT}/api/siem/catalog/tree"
    echo ""
fi
echo -e "${DIM}  Re-run this script at any time to update your configuration.${RESET}"
echo -e "${DIM}  Your previous .env was backed up to .env.bak${RESET}"
echo ""
